package pl.glonojad.pvpgamesmanager.tracker.util;

public enum AttackType {
MELEE, PROJECTILE, TNT, EXPLOSION, FIREBALL, PIERCING, DROWNING, BURNING, SWIMMING, SUICIDE, SUFFOCATION, FALL, SHOCK, FREEZING, STARVATION
}
